AWSTemplateFormatVersion: 2010-09-09
Description: |
  This template launches an EC2 instance which enables SSH.
Resources:
  CFNInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0a8b4cd432b1c3063
      InstanceType: t2.micro
      KeyName: Zack-key
      SecurityGroups: 
        - launch-wizard-7
      Tags:
        - Key: Name
          Value: Kitties
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo yum update -y
          sudo yum install httpd -y
          sudo yum -get install wget 
          cd /var/www/html
          wget https://raw.githubusercontent.com/Zahurul23/Project-pets/master/projects/Project-101-kittens-carousel-static-website-ec2/static-web/Template.yaml
          wget https://raw.githubusercontent.com/Zahurul23/Project-pets/master/projects/Project-101-kittens-carousel-static-website-ec2/static-web/cat0.jpg
          wget https://raw.githubusercontent.com/Zahurul23/Project-pets/master/projects/Project-101-kittens-carousel-static-website-ec2/static-web/cat1.jpg
          wget https://raw.githubusercontent.com/Zahurul23/Project-pets/master/projects/Project-101-kittens-carousel-static-website-ec2/static-web/cat2.jpg
          wget https://raw.githubusercontent.com/Zahurul23/Project-pets/master/projects/Project-101-kittens-carousel-static-website-ec2/static-web/cat3.png
          systemctl enable httpd
          systemctl start httpd  
Outputs:
  URL:
    Value: !Join 
      - ''
      - - 'http://'
        - !GetAtt 
          - CFNInstance
          - PublicIp
    Description: Newly created application URL
